#!/bin/bash
set -euo pipefail

source ../kopano-helper.sh

ensure_config kidmd.cfg
ensure_dir /etc/kopano/kidm/ldif/main.d/

# read settings from kidmd.cfg into env (emulates systemds EnvironmentFile)
sed s/\ *=\ */=/g "/etc/kopano/kidmd.cfg" > /tmp/kidmd-env
# shellcheck disable=SC2046
export $(grep -v '^#' /tmp/kidmd-env | xargs -d '\n')

exec /sbin/setuser kopano /usr/sbin/kopano-kidmd serve