#!/bin/bash
set -euo pipefail

source ../kopano-helper.sh

ensure_config kidmd.cfg
ensure_dir /etc/kopano/kidm/ldif


# read settings from kustomerd.cfg into env (emulates systemds EnvironmentFile)
sed s/\ *=\ */=/g "/etc/kopano/kustomerd.cfg" > /tmp/kustomer-env
# shellcheck disable=SC2046
export $(grep -v '^#' /tmp/kustomer-env | xargs -d '\n')

exec /sbin/setuser kopano /usr/sbin/kopano-kidmd serve