#!/bin/sh

# read settings from kwebd.cfg into env (emulates systemds EnvironmentFile)
sed s/\ *=\ */=/g "/etc/kopano/kwebd.cfg" > /tmp/kweb-env
# shellcheck disable=SC2046
export $(grep -v '^#' /tmp/kweb-env | xargs -d '\n')

/usr/sbin/kopano-kwebd setup

exec /usr/sbin/kopano-kwebd serve